### PR TITLE
Link against and include the CUDA runtime library for C++ code, main branch (2021.03.01.)

### PR DESCRIPTION
**Pull request by krasznaa**
This is a copy of #18, with a couple of my own tweaks on top. See #18 for a more detailed description / discussion about the changes.

### CODE REVIEW

**Comment by krasznaa** [comment]
Hi @stephenswat,

Let's restart our efforts here... I tried to push some changes into #18 first, but you didn't enable that. :frowning: Could you do that for #17? That could speed things up a bit.

Cheers,
         Attila

**Comment by krasznaa** [comment]
> I tried to push some changes into #18 first, but you didn't enable that.  Could you do that for #17? That could speed things up a bit.

Never mind. #17 was fine as it was.

**Comment by stephenswat** [comment]
Looks great! I'll keep the option enabled so you can make commits to my merge requests in the future. I'll close #18!

**Comment by krasznaa** [comment]
The CI is still unable to run, but let's just move ahead with this for now...

**Pull request merged**
