### PR TITLE
Reduce Allocations in Arena Memory Resource, main branch (2021.12.16.)

### PR DESCRIPTION
**Pull request by krasznaa**
Manually copied @Yhatoh's update from #154 into a single commit.

Instead of trying to squash the commits from that PR into a single one, and then rebase it on top of the current main branch (which I tried, but after the second set of conflicts I just gave up), it seemed easier to just create a new commit by hand.

These updates are meant to reduce the number of allocations from the arena allocator. Also fixing an issue in the `vecmem::details::arena` destructor, and hiding `vecmem::details::minimum_superblock_size` from the outside world.

### CODE REVIEW

**Comment by krasznaa** [comment]
@stephenswat, I'd leave the review to you. I'm not convinced I fully understand what the code is doing. :frowning:

**Comment by stephenswat** [comment]
I will take a look at it after lunch. Either way, we should set the author on this commit to `Yhatoh <gacarmonat@gmail.com>`. :smile:

**Comment by Yhatoh** [comment]
Hi!

First at all, happy new year! I wanted to ask in what state is this PR. Do you need more information about the change or maybe do you found something about the changes that are weird?

Cheers,
Gabriel

**Comment by krasznaa** [comment]
Stephen had enough time to raise concerns at this point. :stuck_out_tongue: Since all the existing tests find the changes to be okay, let's just go forward with them. :wink:

**Pull request merged**
