### PR TITLE
HIP CMake Update, main branch (2023.12.29.)

### PR DESCRIPTION
**Pull request by krasznaa**
Triggered by @StewMH's request in #258, and the realization that CMake 3.28 still doesn't work quite right with HIP (https://gitlab.kitware.com/cmake/cmake/-/issues/25541), I put a bit of effort into updating the CMake code managing the HIP source builds in the project.

In VecMem the source file compilation is still happening through the [hipcc](https://github.com/ROCm/HIPCC) compiler front-end. (While CMake's own code rather uses the underlying `clang++` executable directly.) This update just makes sure that the `$HIPFLAGS` environment variable would be properly picked up by the build, and that the CMake code would be a bit more extensible than it was. (By introducing the same "platform configuration file" concept that I added for the SYCL code a while ago.)

While doing this, I had to realize that the linking of HIP binaries was never done quite correctly. More than anything else, by chance, it worked so far. By falling back on the "host linker" for building `vecmem_test_hip`. (Remember, `libvecmem_hip.so` doesn't contain any actual HIP code itself. That, just as `libvecmem_cuda.so`, only contains C\+\+ code.) Which is what we need to do actually, as it turns out. 🤔 Just how the final binary linking of CUDA code happens with the host compiler/linker, I now explicitly set that up for the HIP code as well.
  - First off, as long as one links something that has HIP **and** any other kind of code in it (we're mainly talking about C\+\+ here...), CMake will prefer the "native" C\+\+ linker right away.
  - For binaries that **only** contain HIP source files, the code now explicitly uses `<CMAKE_CXX_COMPILER>` for the linking as well. 🤔

While at it, I also updated `FindHIPToolkit.cmake` to produce variables with names that are more in sync with what [FindCUDAToolkit](https://cmake.org/cmake/help/latest/module/FindCUDAToolkit.html) is doing. And then I made the "HIP language code" make use of `FindHIPToolkit.cmake`, instead of duplicating the header and library search code for itself. (Even if this produces a maybe not great dependency structure in the code. To be seen later on...)

For now I decided to avoid falling back on CMake's own HIP code in our build under any circumstance. Though as I wrote in #258, that's absolutely what I'd like to do at one point. I just fear that I would need to get involved in the CMake project's development for that. 😦

### CODE REVIEW

**Comment by StewMH** [comment]
I looked at this but it doesn't seem to be using `HIP_FLAGS` from the environment or `CMAKE_HIP_FLAGS` (checked with `make VERBOSE=1`)

**Comment by krasznaa** [comment]
The environment variable is called `${HIPFLAGS}`. (Not `${HIP_FLAGS}`. The naming follows [CXXFLAGS](https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html), [CUDAFLAGS](https://cmake.org/cmake/help/latest/envvar/CUDAFLAGS.html), etc.) That one does work. 😉

```
[bash][Celeborn]:build > cmake ../vecmem/
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Looking for a HIP compiler
-- Looking for a HIP compiler - /usr/bin/hipcc
...
[bash][Celeborn]:build > more ./tests/hip/CMakeFiles/vecmem_test_hip.dir/flags.make
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile CXX with /usr/bin/c++
# compile HIP with /usr/bin/hipcc
CXX_FLAGS =  -Wall -Wextra -Wshadow -Wunused-local-typedefs -pedantic -Wconversion -fPIE   -std=gnu++17

CXX_DEFINES = -DVECMEM_DEBUG_MSG_LVL=0 -DVECMEM_HAVE_PMR_MEMORY_RESOURCE -DVECMEM_SOURCE_DIR_LENGTH=44 -D__HIP_PLATFORM_HCC__

CXX_INCLUDES = -I/home/krasznaa/ATLAS/projects/vecmem/build/core/CMakeFiles -I/home/krasznaa/ATLAS/projects/vecmem/vecmem/core/include -I/home/krasznaa/ATLAS/projects/vecmem/build/hip/CMakeFiles -I/home/krasznaa/ATLAS/projects/vecmem/vecmem/hip/include -isystem /opt/rocm/include -isystem /home/krasznaa/ATLAS/projects/vecmem/build/_deps/googletest-src/googletest/include -isystem /home/krasznaa/ATLAS/projects/vecmem/build/_deps/googletest-src/googletest

HIP_FLAGS =      -std=c++14 -fPIE

HIP_DEFINES = -DVECMEM_DEBUG_MSG_LVL=0 -DVECMEM_HAVE_PMR_MEMORY_RESOURCE -DVECMEM_SOURCE_DIR_LENGTH=44 -D__HIP_PLATFORM_HCC__

HIP_INCLUDES = -I/home/krasznaa/ATLAS/projects/vecmem/build/core/CMakeFiles -I/home/krasznaa/ATLAS/projects/vecmem/vecmem/core/include -I/home/krasznaa/ATLAS/projects/vecmem/build/hip/CMakeFiles -I/home/krasznaa/ATLAS/projects/vecmem/vecmem/hip/include -isystem /home/krasznaa/ATLAS/projects/vecmem/build/_deps/googletest-src/googletest/include -isystem /home/krasznaa/ATLAS/projects/vecmem/build/_deps/googletest-src/googletest -isystem /opt/rocm/include

[bash][Celeborn]:build > rm -rf *
[bash][Celeborn]:build > HIPFLAGS="-fPIC" cmake ../vecmem/
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Looking for a HIP compiler
-- Looking for a HIP compiler - /usr/bin/hipcc
...
[bash][Celeborn]:build > more ./tests/hip/CMakeFiles/vecmem_test_hip.dir/flags.make
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile CXX with /usr/bin/c++
# compile HIP with /usr/bin/hipcc
CXX_FLAGS =  -Wall -Wextra -Wshadow -Wunused-local-typedefs -pedantic -Wconversion -fPIE   -std=gnu++17

CXX_DEFINES = -DVECMEM_DEBUG_MSG_LVL=0 -DVECMEM_HAVE_PMR_MEMORY_RESOURCE -DVECMEM_SOURCE_DIR_LENGTH=44 -D__HIP_PLATFORM_HCC__

CXX_INCLUDES = -I/home/krasznaa/ATLAS/projects/vecmem/build/core/CMakeFiles -I/home/krasznaa/ATLAS/projects/vecmem/vecmem/core/include -I/home/krasznaa/ATLAS/projects/vecmem/build/hip/CMakeFiles -I/home/krasznaa/ATLAS/projects/vecmem/vecmem/hip/include -isystem /opt/rocm/include -isystem /home/krasznaa/ATLAS/projects/vecmem/build/_deps/googletest-src/googletest/include -isystem /home/krasznaa/ATLAS/projects/vecmem/build/_deps/googletest-src/googletest

HIP_FLAGS =     -fPIC -std=c++14 -fPIE

HIP_DEFINES = -DVECMEM_DEBUG_MSG_LVL=0 -DVECMEM_HAVE_PMR_MEMORY_RESOURCE -DVECMEM_SOURCE_DIR_LENGTH=44 -D__HIP_PLATFORM_HCC__

HIP_INCLUDES = -I/home/krasznaa/ATLAS/projects/vecmem/build/core/CMakeFiles -I/home/krasznaa/ATLAS/projects/vecmem/vecmem/core/include -I/home/krasznaa/ATLAS/projects/vecmem/build/hip/CMakeFiles -I/home/krasznaa/ATLAS/projects/vecmem/vecmem
/hip/include -isystem /home/krasznaa/ATLAS/projects/vecmem/build/_deps/googletest-src/googletest/include -isystem /home/krasznaa/ATLAS/projects/vecmem/build/_deps/googletest-src/googletest -isystem /opt/rocm/include

[bash][Celeborn]:build >
```

However the `CMAKE_HIP_FLAGS` cache variable indeed doesn't work in the way that it should. 😦 (Something like `cmake -DCMAKE_HIP_FLAGS="-fPIC" ../vecmem/` doesn't work in the way that I would expect...) Let me have another look at the latter. 🤔

**Comment by krasznaa** [comment]
Played with it a bit... 🤔 Using both `HIPFLAGS=foo` or `-DCMAKE_HIP_FLAGS=bar` should work with this latest version. The latter seems to work even better than I remembered `CMAKE_CXX_FLAGS` working. 😕 With the version of CMake that I used for the development, both `-DCMAKE_CXX_FLAGS=Foo` and `-DCMAKE_HIP_FLAGS=Bar` ended up adding to the standard flags, and didn't remove any of them. Which is not how I remember things working in the past... (Note though that when specifying both the environment and cache variables at the same time, only the cache variable setting takes effect. Which is in sync with how `CXXFLAGS` and `CMAKE_CXX_FLAGS` behave.)

Still, if this works, then great! 😄

I'll also need to update the SYCL code with some of the lessons learned from this exercise... 🤔

**Comment by krasznaa** [comment]
@StewMH, did you have a chance to try this code on your machine? Before I completely forget all the details, I'd like to merge it in, and then update the SYCL code a little based on what I learned in this PR.

But only if you don't find any more obvious issues with these changes. :wink:

**Comment by StewMH** [comment]
Hi Attila,

I have some sort of issue:
```
CMake Error at /scratch/smh/updateTraccc/bld/_deps/vecmem-src/cmake/hip/CMakeDetermineHIPCompiler.cmake:101 (find_package):
  By not providing "FindHIPToolkit.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "HIPToolkit", but CMake did not find one.

  Could not find a package configuration file provided by "HIPToolkit" with
  any of the following names:

    HIPToolkitConfig.cmake
    hiptoolkit-config.cmake

  Add the installation prefix of "HIPToolkit" to CMAKE_PREFIX_PATH or set
  "HIPToolkit_DIR" to a directory containing one of the above files.  If
  "HIPToolkit" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  device/alpaka/CMakeLists.txt:19 (enable_language)
```
when I use it with traccc. However it seems to work standalone (at least it all compiles, there are problems when running tests that I suspect are unrelated).

**Comment by krasznaa** [comment]
🤔 Very good that you tested that!

I'm now indeed doing something a bit new with how the "HIP language" makes use of `FindHIPToolkit.cmake`. Which unfortunately I'm still not 100% sure, is a good idea. 🤔 Still, for now let's just fix this issue that you found...

**Comment by krasznaa** [comment]
This issue is now fixed with the latest update. But... how did you test HIP usage in traccc so far? Did you test it at all? :confused:

Right now these two files prevent HIP compilation for an AMD backend:
  - https://github.com/acts-project/detray/blob/main/core/include/detray/definitions/qualifiers.hpp
  - https://github.com/acts-project/traccc/blob/main/core/include/traccc/definitions/qualifiers.hpp

I fixed the latter in my test build, but at that point the Detray code is still producing an error.

```
...
[100%] Building HIP object device/alpaka/CMakeFiles/traccc_alpaka.dir/src/utils/make_prefix_sum_buff.cpp.o
Warning: HIP_PLATFORM=hcc is deprecated. Please use HIP_PLATFORM=amd. 
[100%] Building HIP object device/alpaka/CMakeFiles/traccc_alpaka.dir/src/seeding/spacepoint_binning.cpp.o
Warning: HIP_PLATFORM=hcc is deprecated. Please use HIP_PLATFORM=amd. 
In file included from /mnt/hdd1/krasznaa/projects/traccc/traccc/device/alpaka/src/seeding/spacepoint_binning.cpp:16:
In file included from /mnt/hdd1/krasznaa/projects/traccc/traccc/device/common/include/traccc/seeding/device/populate_grid.hpp:41:
/mnt/hdd1/krasznaa/projects/traccc/traccc/device/common/include/traccc/seeding/device/impl/populate_grid.ipp:33:24: error: no matching constructor for initialization of 'sp_grid_device' (aka 'grid2<detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, vecmem::device_vector, vecmem::jagged_device_vector, detray::darray, detray::dtuple, internal_spacepoint<spacepoint>, false>')
        sp_grid_device grid(grid_view);
                       ^    ~~~~~~~~~
/mnt/hdd1/krasznaa/projects/traccc/build/_deps/detray-src/core/include/detray/grids/grid2.hpp:46:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'sp_grid_view' (aka 'grid2_view<grid2<detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, detray::dvector, detray::djagged_vector, detray::darray, detray::dtuple, internal_spacepoint<spacepoint>, false>>') to 'const grid2<detray::attach_populator, detray::axis::circular, detray::axis::regular, serializer2, vecmem::device_vector, vecmem::jagged_device_vector, detray::darray, detray::dtuple, internal_spacepoint<spacepoint>>' for 1st argument
class grid2 {
      ^
/mnt/hdd1/krasznaa/projects/traccc/build/_deps/detray-src/core/include/detray/grids/grid2.hpp:46:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'sp_grid_view' (aka 'grid2_view<grid2<detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, detray::dvector, detray::djagged_vector, detray::darray, detray::dtuple, internal_spacepoint<spacepoint>, false>>') to 'grid2<detray::attach_populator, detray::axis::circular, detray::axis::regular, serializer2, vecmem::device_vector, vecmem::jagged_device_vector, detray::darray, detray::dtuple, internal_spacepoint<spacepoint>>' for 1st argument
/mnt/hdd1/krasznaa/projects/traccc/build/_deps/detray-src/core/include/detray/grids/grid2.hpp:67:5: note: candidate constructor not viable: call to __host__ function from __device__ function
    grid2(vecmem::memory_resource &mr,
    ^
/mnt/hdd1/krasznaa/projects/traccc/build/_deps/detray-src/core/include/detray/grids/grid2.hpp:117:24: note: candidate constructor not viable: call to __host__ function from __device__ function
    DETRAY_HOST_DEVICE grid2(
                       ^
...
```

So... did you only test HIP with its NVIDIA backend so far? But then why would you be championing HIP quite so much? :confused:

P.S. Both those files will need to be updated like: https://github.com/acts-project/vecmem/blob/main/core/include/vecmem/utils/types.hpp

**Comment by StewMH** [comment]
Hi Attila,

Thanks for the fix. I've been trying to get @CrossR's Alpaka traccc port working with HIP + AMD backend for about a month now. I had managed to work around the cmake problems but not solved any compilation isues yet. You can see the rough progress here: https://codimd.web.cern.ch/s/reqItO-uf#

**Comment by krasznaa** [comment]
Okay. Let's get this in then. And then start fixing up the other projects for HIP...

**Pull request merged**
